# File test API - nhờ attention là Rest Client trên VSCode

GET http://localhost:5000/api/get-product
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzBkZGMyMjZjNWFmMmUyMDYxMjM1ZGIiLCJpYXQiOjE2NjE5MTU0NTQsImV4cCI6MTY2MjAwMTg1NH0.BQ0OQgat7lVEEYpJi6SaIpeIBjtC6Ub3sn25NEDtjYs

###

GET http://localhost:5000/api/get-product/6312baad160cb5e9a150f418
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzBkZGMyMjZjNWFmMmUyMDYxMjM1ZGIiLCJpYXQiOjE2NjE5MTU0NTQsImV4cCI6MTY2MjAwMTg1NH0.BQ0OQgat7lVEEYpJi6SaIpeIBjtC6Ub3sn25NEDtjYs

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "bac@gmail.com",
    "password": "6688"
}

###
POST http://localhost:5000/user/signup
Content-Type: application/json

{
    "_id": "104314380891398686045888",
    "name": "vxbac",
    "email": "test11@gmail.com",
    "phone": "0989878909",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTPB2nPBCDu7poAPxLGeng3gOJFKN6IkYV9-9B8Y2H&s",
    "password": "6688"
}

###
POST http://localhost:5000/api/create-product
Content-Type: application/json

{
    "title": "Áo thun đẹp",
    "description": "Chất vải thoáng mát, lịch lãm không phai màu",
    "category": "productnam",
    "price": 1000,
    "image": "https://media.loveitopcdn.com/853/ao-thun-nam-cotton-tho-nau-1.jpg"
}

###
POST http://localhost:5000/category/create-category
Content-Type: application/json

{
    "name": "Product Nữ"
}

###
POST http://localhost:5000/bill/create-bill
Content-Type: application/json

{
    "amount": "2",
    "total_price": "99000",
    "phone": "0868609878",
    "address": "Đắk Lắk",
    "status": "1",
    "products": "6312baad160cb5e9a150f418",
    "users": "6311c98f941617c9ab92fcfe"
}

###

GET http://localhost:5000/bill/get-all

###
POST http://localhost:5000/other/create-other
Content-Type: application/json

{
    "web_title": "SHOP",
    "web_hotline": "0868609878",
    "web_mail": "vubacbds@gmail.com",
    "web_facebook": "https://fb.com/",
    "web_youtube": "https://www.youtube.com/",
    "web_finish": "© 2022 Copyright:  Website built on ReactJS and NodeJS platform by BAC",
    "web_cs": "Chính sách mua hàng",
    "web_bh": "Bảo hành",
    "web_hd": "Hướng dẫn",
    "web_linkads": "https://blog.freelancerviet.vn/5-nguyen-tac-vang-de-thiet-ke-banner-cho-website/" ,
    "web_imageads": "https://blog.freelancerviet.vn/wp-content/uploads/2019/03/nguyen_tac_thiet_ke_banner_31.jpg" 
}

###

GET http://localhost:5000/other/get-other

###
PUT http://localhost:5000/other/update-other/631d9f048f553b1a6f50b9a7
Content-Type: application/json

{
    "web_title": "SHOPS",
    "web_hotline": "0868609878",
    "web_mail": "vubacbds@gmail.com",
    "web_facebook": "https://fb.com/",
    "web_youtube": "https://www.youtube.com/"
}

###

POST http://localhost:5000/evaluation/create-evaluation
Content-Type: application/json

{
    "body": "Đánh gía đầu tiên",
    "image": "https://blog.freelancerviet.vn/wp-content/uploads/2019/03/nguyen_tac_thiet_ke_banner_31.jpg",
    "products": "631b1a98ba348d830455df28",
    "users": "6311c98f941617c9ab92fcfe"
}

###
GET http://localhost:5000/evaluation/get-evaluation/631b1a98ba348d830455df28/1
Content-Type: application/json



###
POST http://localhost:5000/size/create-size
Content-Type: application/json

{
    "name": "Size L",
    "status": "0"
}


###
POST http://localhost:5000/color/create-color
Content-Type: application/json

{
    "name": "Màu Xanh",
    "status": "0"
}


###
GET http://localhost:5000/user/get-email
Content-Type: application/json

{
    "email": "bac0122000@gmail.com"
}

###
POST http://localhost:5000/reply/create-reply
Content-Type: application/json

{
   "body": "Đánh gía thứ hai",
    "likes": ["89898782"],
    "users": "6311c98f941617c9ab92fcfe"
}